[0m22:10:11.408952 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f90bb4ff430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f90bd446ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f90bd459670>]}


============================== 22:10:11.417068 | 74170593-2293-4f46-a6a6-1ccaeb6920d7 ==============================
[0m22:10:11.417068 [info ] [MainThread]: Running with dbt=1.7.11
[0m22:10:11.417978 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/cloudai/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:10:11.418770 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/cloudai/.dbt')}
[0m22:10:11.419378 [info ] [MainThread]: Creating dbt configuration folder at 
[0m22:10:24.916297 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dbt/include/starter_project
[0m22:10:24.927559 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:10:24.928192 [info ] [MainThread]: Setting up your profile.
[0m22:10:24.929119 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m22:10:24.944761 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 13.551218, "process_user_time": 1.945293, "process_kernel_time": 0.152479, "process_mem_max_rss": "84865024", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m22:10:24.945720 [debug] [MainThread]: Command `dbt init` failed at 22:10:24.945497 after 13.55 seconds
[0m22:10:24.946316 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f90bb4ff430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f90bd446910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f90bd446940>]}
[0m22:10:24.946845 [debug] [MainThread]: Flushing usage events
